// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Task struct {
	ID          string     `json:"id"`
	UserID      string     `json:"userId"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Status      TaskStatus `json:"status"`
	DueDate     string     `json:"dueDate"`
	CreatedAt   string     `json:"createdAt"`
	UpdatedAt   string     `json:"updatedAt"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type TaskStatus string

const (
	TaskStatusCompleted  TaskStatus = "COMPLETED"
	TaskStatusInprogress TaskStatus = "INPROGRESS"
	TaskStatusPending    TaskStatus = "PENDING"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusCompleted,
	TaskStatusInprogress,
	TaskStatusPending,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusCompleted, TaskStatusInprogress, TaskStatusPending:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
